/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.StockDAO;
import Model.Stock;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ManageCheckStock extends javax.swing.JPanel {

    private int index = -1;
    StockDAO stock = new StockDAO();
    int id = 1;

    /**
     * Creates new form CheckStockPanel
     */
    public ManageCheckStock() {
        initComponents();
        Hide();
        checkStock();
    }

    public void checkStock() {
        DefaultTableModel model = (DefaultTableModel) jTableCheckStock.getModel();
        model.setRowCount(0);
        for (int i = 0; i < stock.getAll().size(); i++) {
            model.addRow(new Object[]{stock.getAll().get(i).getId(),
                stock.getAll().get(i).getName(),
                stock.getAll().get(i).getPrice(),
                stock.getAll().get(i).getUnit()});
        }
    }

    public void Hide() {
        ButSave.setEnabled(false);
        ButCancel.setEnabled(false);
        InputName.setEditable(false);
        InputPrice.setEditable(false);
        InputUnit.setEditable(false);
    }

    public void Show() {
        ButSave.setEnabled(true);
        ButCancel.setEnabled(true);
        InputName.setEditable(true);
        InputPrice.setEditable(true);
        InputUnit.setEditable(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCheckStock = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        JLabelFind = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputPrice = new javax.swing.JTextField();
        ButEdit = new javax.swing.JButton();
        ButDel = new javax.swing.JButton();
        ButAdd = new javax.swing.JButton();
        ButCancel = new javax.swing.JButton();
        ButSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        InputUnit = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));

        jTableCheckStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "PRICE", "UNIT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCheckStock);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JLabelFind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("NAME :");

        jLabel3.setText("PRICE :");

        ButEdit.setText("Edit");
        ButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButEditActionPerformed(evt);
            }
        });

        ButDel.setText("Delete");
        ButDel.setMaximumSize(new java.awt.Dimension(51, 23));
        ButDel.setMinimumSize(new java.awt.Dimension(51, 23));
        ButDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDelActionPerformed(evt);
            }
        });

        ButAdd.setText("Add");
        ButAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAddActionPerformed(evt);
            }
        });

        ButCancel.setText("Cancel");
        ButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelActionPerformed(evt);
            }
        });

        ButSave.setText("Save");
        ButSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("UNIT :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLabelFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InputName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(JLabelFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(InputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(InputUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDelActionPerformed
        index = jTableCheckStock.getSelectedRow();
        if (index == -1) {
            int reply = JOptionPane.showConfirmDialog(null, "please select Row Delete", "Delete ", JOptionPane.DEFAULT_OPTION);
            return;
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?"
                    + "", "Delete Product", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                stock.delete(index+1);

            }
        }
        checkStock();
    }//GEN-LAST:event_ButDelActionPerformed

    private void ButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButEditActionPerformed
        index = jTableCheckStock.getSelectedRow();
        if (index == -1) {
            int reply = JOptionPane.showConfirmDialog(null, "please select Row Edit ", "Edit ", JOptionPane.DEFAULT_OPTION);
            return;
        } else if (index > -1) {
            Show();
            ArrayList<Stock> stock = this.stock.getAll();
            id = stock.get(index).getId();
            InputName.setText(stock.get(index).getName());
            InputPrice.setText(String.valueOf(stock.get(index).getPrice()));
            InputUnit.setText(String.valueOf(stock.get(index).getUnit()));

        } else {
            System.out.println("Can't Edit");
        }

        checkStock();
    }//GEN-LAST:event_ButEditActionPerformed

    private void ButAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAddActionPerformed
        Show();
    }//GEN-LAST:event_ButAddActionPerformed

    private void ButSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSaveActionPerformed
        StockDAO stock = new StockDAO();
        int q = Integer.parseInt(InputUnit.getText());
        double p = Double.parseDouble(InputPrice.getText());
        if(index == -1){
            stock.add(new Stock(-1,q,InputName.getText(),p));
        }else{
            stock.update(new Stock(index+1,q,InputName.getText(),p));
        }
        
        Clear();
        checkStock();
        Hide();
    }//GEN-LAST:event_ButSaveActionPerformed
    public void Clear() {
        jTextField1.setText("");
        InputName.setText("");
        InputPrice.setText("");
        InputUnit.setText("");

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int q = Integer.parseInt(jTextField1.getText());
        for (int i = 0; i < stock.getAll().size(); i++) {
            if (q == stock.getAll().get(i).getId()) {
                JLabelFind.setText("Find : ID " + stock.getAll().get(i).getId()
                        + " Name: " + stock.getAll().get(i).getName()
                        + " Price: " + stock.getAll().get(i).getPrice()
                        + " Unit: " + stock.getAll().get(i).getUnit());
            }
        }
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelActionPerformed
        Clear();
        Hide();
    }//GEN-LAST:event_ButCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAdd;
    private javax.swing.JButton ButCancel;
    private javax.swing.JButton ButDel;
    private javax.swing.JButton ButEdit;
    private javax.swing.JButton ButSave;
    private javax.swing.JTextField InputName;
    private javax.swing.JTextField InputPrice;
    private javax.swing.JTextField InputUnit;
    private javax.swing.JLabel JLabelFind;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCheckStock;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
