/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.User;

/**
 *
 * @author ASUS
 */
public class MenuBarPanel extends javax.swing.JPanel {

    private final MainPanel mainPanel;

    /**
     * Creates new form MenuBarPanel
     */
    public MenuBarPanel(MainPanel mainPanel) {
        initComponents();
        this.mainPanel = mainPanel;
        currentUserName.setText(mainPanel.currentUser.getName());
        currentUserRole.setText(mainPanel.currentUser.getRole());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentUserContainer = new javax.swing.JPanel();
        btnOut = new javax.swing.JButton();
        currentUserName = new javax.swing.JLabel();
        currentUserRole = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        containerScroll = new javax.swing.JScrollPane();
        screenContainer = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 800));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(930, 600));

        currentUserContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnOut.setText("Logout");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        currentUserName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        currentUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentUserName.setText("name");

        currentUserRole.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        currentUserRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentUserRole.setText("Role");
        currentUserRole.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout currentUserContainerLayout = new javax.swing.GroupLayout(currentUserContainer);
        currentUserContainer.setLayout(currentUserContainerLayout);
        currentUserContainerLayout.setHorizontalGroup(
            currentUserContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentUserContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentUserContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentUserRole, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOut)
                .addContainerGap())
        );
        currentUserContainerLayout.setVerticalGroup(
            currentUserContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentUserContainerLayout.createSequentialGroup()
                .addGroup(currentUserContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(currentUserContainerLayout.createSequentialGroup()
                        .addComponent(currentUserRole)
                        .addGap(1, 1, 1)
                        .addComponent(currentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(currentUserContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerScroll.setMinimumSize(new java.awt.Dimension(910, 510));
        containerScroll.setPreferredSize(new java.awt.Dimension(910, 510));

        screenContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        screenContainer.setMaximumSize(new java.awt.Dimension(900, 500));
        screenContainer.setMinimumSize(new java.awt.Dimension(900, 500));
        screenContainer.setPreferredSize(new java.awt.Dimension(900, 500));

        javax.swing.GroupLayout screenContainerLayout = new javax.swing.GroupLayout(screenContainer);
        screenContainer.setLayout(screenContainerLayout);
        screenContainerLayout.setHorizontalGroup(
            screenContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        screenContainerLayout.setVerticalGroup(
            screenContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        containerScroll.setViewportView(screenContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(containerScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(323, 323, 323)
                        .addComponent(currentUserContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentUserContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(containerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        mainPanel.logout();
        currentUserName.setText("Name");
        currentUserRole.setText("Role");
    }//GEN-LAST:event_btnOutActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOut;
    private javax.swing.JScrollPane containerScroll;
    private javax.swing.JPanel currentUserContainer;
    private javax.swing.JLabel currentUserName;
    private javax.swing.JLabel currentUserRole;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel screenContainer;
    // End of variables declaration//GEN-END:variables
}
