/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.ProductDAO;
import Model.Customer;
import Model.OrderUI;
import Model.Product;
import Model.Receipt;
import Model.ReceiptDetail;
import Model.User;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
//import UI.ProductPanel.OnBuyListener;

/**
 *
 * @author ASUS
 */
public class MenuPanel extends javax.swing.JPanel /*implements OnBuyListener*/ {

    private final ArrayList<Product> productList;
    private final ArrayList<ReceiptDetail> receiptDetailList;

    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
        //Call Menu data from Mockup(DB)
        ProductDAO pDAO = new ProductDAO();
        productList = pDAO.getAll();
        receiptDetailList = ReceiptDetail.testReceiptDetail();
        generateMenu();
        generateOrder();
        genOrder();
    }

    public void generateMenu() {
        int productSize = productList.size();
        productSize = productSize / 3 + productSize % 3;
        productSelector.setLayout(new GridLayout(productSize, 3));
        productSelector.setMinimumSize(new Dimension(480, (productSize * 200)));
        productSelector.setPreferredSize(new Dimension(480, (productSize * 200)));
        for (Product product : productList) {
            ProductPanel p = new ProductPanel(product, this);
//            p.addOnBuyListener(subscriber);
//Error
            productSelector.add(p);
        }
    }

    public void generateOrder() {
        int orderSize = receiptDetailList.size();
        orderPanel.setLayout(new GridLayout(orderSize, 1));
        orderPanel.setMinimumSize(new Dimension(90, (orderSize * 50)));
        orderPanel.setPreferredSize(new Dimension(90, (orderSize * 50)));
        for (ReceiptDetail recDetail : receiptDetailList) {
            OrderPanel p = new OrderPanel(recDetail, this);
            orderPanel.add(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        productSelectorScroll = new javax.swing.JScrollPane();
        productSelector = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        vat = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        change = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        grandTotal = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));

        jPanel3.setBackground(new java.awt.Color(125, 96, 57));
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 400));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 400));

        jButton2.setBackground(new java.awt.Color(250, 233, 215));
        jButton2.setForeground(new java.awt.Color(125, 96, 57));
        jButton2.setText("OK");

        jButton1.setBackground(new java.awt.Color(250, 233, 215));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(125, 96, 57));
        jButton1.setText("Register");

        jButton3.setBackground(new java.awt.Color(250, 233, 215));
        jButton3.setForeground(new java.awt.Color(125, 96, 57));
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(250, 233, 215));
        jButton4.setForeground(new java.awt.Color(125, 96, 57));
        jButton4.setText("Cancel");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 243, 230));
        jLabel1.setText("Order : ");

        productSelectorScroll.setBackground(new java.awt.Color(240, 204, 95));
        productSelectorScroll.setMaximumSize(new java.awt.Dimension(500, 300));
        productSelectorScroll.setMinimumSize(new java.awt.Dimension(500, 300));
        productSelectorScroll.setPreferredSize(new java.awt.Dimension(500, 300));

        productSelector.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 96, 57)));
        productSelector.setMinimumSize(new java.awt.Dimension(480, 300));
        productSelector.setPreferredSize(new java.awt.Dimension(480, 1000));
        productSelector.setLayout(new java.awt.GridLayout(10, 3));
        productSelectorScroll.setViewportView(productSelector);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(100, 60));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(100, 60));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 60));

        orderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 96, 57)));
        orderPanel.setMaximumSize(new java.awt.Dimension(100, 200));
        orderPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        orderPanel.setPreferredSize(new java.awt.Dimension(100, 200));
        orderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderPanelMouseEntered(evt);
            }
        });
        orderPanel.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane2.setViewportView(orderPanel);

        jPanel5.setBackground(new java.awt.Color(255, 243, 230));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 96, 57)));

        jLabel3.setForeground(new java.awt.Color(125, 96, 57));
        jLabel3.setText("Total ");

        jLabel4.setForeground(new java.awt.Color(125, 96, 57));
        jLabel4.setText("Vat");

        jLabel5.setForeground(new java.awt.Color(125, 96, 57));
        jLabel5.setText("Member Discount (10%) ");

        jLabel6.setForeground(new java.awt.Color(125, 96, 57));
        jLabel6.setText("Cash");

        jLabel7.setForeground(new java.awt.Color(125, 96, 57));
        jLabel7.setText("Change");

        total.setForeground(new java.awt.Color(125, 96, 57));
        total.setText("0.00");

        vat.setForeground(new java.awt.Color(125, 96, 57));
        vat.setText("0.00");

        jLabel9.setForeground(new java.awt.Color(125, 96, 57));
        jLabel9.setText("0.00");

        cash.setBackground(new java.awt.Color(255, 243, 230));
        cash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cashFocusLost(evt);
            }
        });
        cash.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cashInputMethodTextChanged(evt);
            }
        });
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });
        cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashKeyTyped(evt);
            }
        });

        change.setForeground(new java.awt.Color(125, 96, 57));
        change.setText("0.00");

        jLabel2.setForeground(new java.awt.Color(125, 96, 57));
        jLabel2.setText("Grand Total");

        grandTotal.setForeground(new java.awt.Color(125, 96, 57));
        grandTotal.setText("0.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vat))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(change))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grandTotal)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(vat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grandTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(change))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(productSelectorScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(430, 430, 430)
                            .addComponent(jButton1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(127, 127, 127))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productSelectorScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void orderPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderPanelMouseEntered
        updateTotal();
    }//GEN-LAST:event_orderPanelMouseEntered

    private void cashInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cashInputMethodTextChanged

    }//GEN-LAST:event_cashInputMethodTextChanged

    private void cashFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashFocusLost

    }//GEN-LAST:event_cashFocusLost

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashActionPerformed


    private void cashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashKeyTyped

    }//GEN-LAST:event_cashKeyTyped

    private void cashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashKeyReleased
        try{
            double grandTotalPrice = Double.parseDouble(grandTotal.getText());
            double cash = Double.parseDouble(this.cash.getText());
            System.out.println(cash);
            this.change.setText(String.valueOf(new DecimalFormat("##.##").format(cash - grandTotalPrice)));
        }catch(Exception e){
            System.out.println("Cash must be not null or empty.\n"+e);
        }
        
    }//GEN-LAST:event_cashKeyReleased
//    private final ArrayList<ReceiptDetail> receipt = ReceiptDetail.testReceiptDetail();
//    @Override
//    public void buy(Product product) {
//        System.out.println("In");
//        System.out.println("");
//        User seller = new User(1,"winwin","0888888888","Employee","password1","user1");
//        Customer customer = new Customer(1,"Somsri","0801111111",0);
//        receiptDetailList.add(new ReceiptDetail(product,1,product.getPrice(),new Receipt(seller,customer)));
//        generateOrder();
//
//    }

    public void genOrder() {
        orderPanel.removeAll();
        orderPanel.revalidate();
        orderPanel.repaint();
        int orderSize = countedOrders.size();
        orderPanel.setLayout(new GridLayout(orderSize, 1));
        orderPanel.setMinimumSize(new Dimension(90, (orderSize * 50)));
        orderPanel.setPreferredSize(new Dimension(90, (orderSize * 50)));
        User seller = new User(1, "winwin", "0888888888", "Employee", "password1", "user1");
        Customer customer = new Customer(1, "Somsri", "0801111111", 0);
        for (int i = 0; i < countedOrders.size(); i++) {
            OrderPanel orp = new OrderPanel(new ReceiptDetail(countedOrders.get(i).getProduct(), countedOrders.get(i).getAmount(), countedOrders.get(i).getProduct().getPrice(), new Receipt(seller, customer)), this);
            orderPanel.add(orp);
        }
//        for(OrderUI recDetail : countedOrders){
//            OrderPanel orp = new OrderPanel(recDetail);
//            orderPanel.add(orp);
//        }
//        for (ReceiptDetail recDetail : receiptDetailList) {
//            OrderPanel p = new OrderPanel(recDetail);
//            orderPanel.add(p);
//        }
    }

    public void addCountedOrder(OrderUI order) {
        for (int i = 0; i < countedOrders.size(); i++) {
            if (order.getProduct().getName().equals(countedOrders.get(i).getProduct().getName())) {
                countedOrders.get(i).addAmount();
                genOrder();
                System.out.println(countedOrders.toString());
                updateTotal();
                return;
            }
        }
        countedOrders.add(order);
        genOrder();
        System.out.println(countedOrders.toString());
        updateTotal();
    }

    public void updateCountedOrders(OrderUI order) {
        for (int i = 0; i < countedOrders.size(); i++) {
            if (order.getProduct().getName().equals(countedOrders.get(i).getProduct().getName())) {
                countedOrders.get(i).setAmount(order.getAmount());
                return;
            }
        }
        updateTotal();
    }

    public void updateTotal() {
        double total = 0;
        for (int i = 0; i < countedOrders.size(); i++) {
            total += countedOrders.get(i).getPrice() * countedOrders.get(i).getAmount();
        }
        this.total.setText(String.valueOf(total));
        vat.setText(new DecimalFormat("##.##").format(total * 0.07));
        grandTotal.setText(String.valueOf(total + Double.parseDouble(vat.getText())));
    }
    public ArrayList<OrderUI> countedOrders = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cash;
    private javax.swing.JLabel change;
    private javax.swing.JLabel grandTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JPanel productSelector;
    private javax.swing.JScrollPane productSelectorScroll;
    private javax.swing.JLabel total;
    private javax.swing.JLabel vat;
    // End of variables declaration//GEN-END:variables
}
