/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Product;
import Model.ReceiptDetail;

/**
 *
 * @author Xenon
 */
public class OrderPanel extends javax.swing.JPanel {

    private final ReceiptDetail receiptDetail;
    /**
     * Creates new form OrderPanel
     */
    public OrderPanel(ReceiptDetail receiptDetail) {
        initComponents();
        this.receiptDetail = receiptDetail;
        setOrderData(receiptDetail);
    }
    
    public void setOrderData(ReceiptDetail receiptDetail) {
        orderLbl.setText(receiptDetail.getProduct().getName());
        amountLbl.setText("" + receiptDetail.getAmount());
        priceLbl.setText("" + receiptDetail.getPrice());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderLbl = new javax.swing.JLabel();
        minusBtn = new javax.swing.JButton();
        amountLbl = new javax.swing.JLabel();
        plusBtn = new javax.swing.JButton();
        priceLbl = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 243, 230));

        orderLbl.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        orderLbl.setForeground(new java.awt.Color(125, 96, 57));
        orderLbl.setText("Order");

        minusBtn.setBackground(new java.awt.Color(255, 227, 189));
        minusBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        minusBtn.setForeground(new java.awt.Color(102, 102, 102));
        minusBtn.setText("-");
        minusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBtnActionPerformed(evt);
            }
        });

        amountLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amountLbl.setForeground(new java.awt.Color(125, 96, 57));
        amountLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountLbl.setText("0");

        plusBtn.setBackground(new java.awt.Color(255, 227, 189));
        plusBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plusBtn.setForeground(new java.awt.Color(102, 102, 102));
        plusBtn.setText("+");
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        priceLbl.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        priceLbl.setForeground(new java.awt.Color(125, 96, 57));
        priceLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl.setText("0.00");
        priceLbl.setAutoscrolls(true);
        priceLbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        delBtn.setBackground(new java.awt.Color(255, 227, 189));
        delBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delBtn.setForeground(new java.awt.Color(102, 102, 102));
        delBtn.setText("X");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minusBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plusBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderLbl)
                    .addComponent(minusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLbl)
                    .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLbl)
                    .addComponent(delBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void minusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minusBtnActionPerformed

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLbl;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton minusBtn;
    private javax.swing.JLabel orderLbl;
    private javax.swing.JButton plusBtn;
    private javax.swing.JLabel priceLbl;
    // End of variables declaration//GEN-END:variables
}
